[phases.setup]
aptPkgs = ["wget", "dpkg", "python3"]

[phases.build]
cmds = [
  "wget -O mypackage.deb https://raw.githubusercontent.com/YOUR_GITHUB_USER/YOUR_REPO/main/mypackage.deb"
]

[phases.start]
cmds = ["python3 -m http.server 8080"]
