[phases.setup]
aptPkgs = ["wget", "dpkg", "python3"]

[phases.build]
cmds = [
  "wget -O mypackage.deb https://raw.githubusercontent.com/C-S23/log-archiveTool/main/mypackage.deb"
]

[phases.start]
cmds = ["python3 -m http.server 8080"]

[phases.setup]
aptPkgs = ["wget", "dpkg", "python3"]
[phases.build]
cmds = ["echo 'Build Phase Complete'"]
[phases.start]
cmds = ["python3 -m http.server 8080"]
